### ISSUE TITLE
Translation not applied in dropdown selection (card search)

### ISSUE THREAD

**Issue by hwahyang1** [MalitsPlus/HoshimiStage#276]
![image](https://github.com/MalitsPlus/HoshimiStage/assets/40535405/a177693f-89a8-4107-85ad-1bfdce2fab5c)

**Comment by MalitsPlus** [comment]
This is caused by my inappropriate practice of using `i18next`

https://github.com/MalitsPlus/HoshimiStage/blob/83ede0dcc80ef84f979f914b2001814519a5bcbe/components/search/SearchOptions.tsx#L125-L126

I placed `t()` in the field of `useState`, this causes preset strings cannot be updated during switching languages (rerendering) since the states was never been changed. 

I will come up with a solution in few days.
